
const fs = require('fs');
const path = require('path');

const ocrText = `
AMCOR.NMT037
PF* CIA_CODCIA VARCHAR2 (4 BYTE) PF* TNOM_TIPNOM VARCHAR2 (4 BYTE) PF* PROC_TIPPRO NUMBER (2) PF* FPRO_SUBPRO NUMBER (1) PF* FPRO_ANOCAL NUMBER (4) PF* FPRO_NUMPER NUMBER (3) P * SUBTIP VARCHAR2 (1 BYTE) P * FICTRA VARCHAR2 (10 BYTE) EXCTXT VARCHAR2 (1 BYTE) LINEA1 VARCHAR2 (40 BYTE) LINEA2 VARCHAR2 (40 BYTE) LINEA3 VARCHAR2 (40 BYTE) LINEA4 VARCHAR2 (40 BYTE) USRCRE VARCHAR2 (30 BYTE) FECCRE DATE USRACT VARCHAR2 (30 BYTE) FECACT DATE
AMCOR.SPI_USUARIO
P * ID VARCHAR2 (60 BYTE) F ID_PERSONA NUMBER (20) * CLAVE_ACCESO VARCHAR2 (150 BYTE) PREG_SECRETA VARCHAR2 (60 BYTE) RESP_SECRETA VARCHAR2 (32 BYTE) F ID_PERFIL VARCHAR2 (32 BYTE) F ID_PAIS VARCHAR2 (4 BYTE) E_MAIL VARCHAR2 (60 BYTE) USRCRE VARCHAR2 (60 BYTE) FECCRE DATE USRACT VARCHAR2 (60 BYTE) FECACT DATE CAMBIO_CLAVE DATE INACTIVO VARCHAR2 (1 BYTE) IDIOMA NUMBER (1) * ID_ACCESO VARCHAR2 (150 BYTE) INTENTOS NUMBER (2) FECHA_ACCE DATE
AMCOR.TA_RELACION_LABORAL
PF* ID_EMPRESA VARCHAR2 (4 BYTE) P * FICHA VARCHAR2 (10 BYTE) F * ID_PERSONA NUMBER (20) F_INGRESO DATE F_CORPORACION DATE F_AJUSTADA1 DATE F_AJUSTADA2 DATE F_AJUSTADA3 DATE F ID_LOCALIDAD VARCHAR2 (4 BYTE) F ID_CATEGORIA1 VARCHAR2 (4 BYTE) F ID_CATEGORIA2 VARCHAR2 (4 BYTE) F ID_CATEGORIA3 VARCHAR2 (4 BYTE) F ID_SINDICATO VARCHAR2 (4 BYTE) ID_CENTRO_MED VARCHAR2 (4 BYTE) NRO_RIF VARCHAR2 (15 BYTE) NRO_SSO VARCHAR2 (12 BYTE) F_RETIRO DATE F ID_FINIQUITO VARCHAR2 (4 BYTE) F_CONTRATO DATE NRO_TARJETA VARCHAR2 (5 BYTE) F ID_PROFESION VARCHAR2 (4 BYTE) F_GRADUACION DATE F ID_NIVEL_EDU VARCHAR2 (1 BYTE) ANO_APROBADO NUMBER (2) F ID_GRADO VARCHAR2 (6 BYTE) INI_GRADO DATE AUMENTO_GRADO VARCHAR2 (1 BYTE) USRCRE VARCHAR2 (60 BYTE) FECCRE DATE USRACT VARCHAR2 (60 BYTE) FECACT DATE FICHA_JEFE VARCHAR2 (10 BYTE) F HORARIO1 VARCHAR2 (4 BYTE) F HORARIO2 VARCHAR2 (4 BYTE) F HORARIO3 VARCHAR2 (4 BYTE) F HORARIO4 VARCHAR2 (4 BYTE) F HORARIO5 VARCHAR2 (4 BYTE) CUSPP VARCHAR2 (16 BYTE)
AMCOR.EO_CARGO
PF* ID_EMPRESA VARCHAR2 (4 BYTE) P * ID VARCHAR2 (10 BYTE) * NOMBRE VARCHAR2 (50 BYTE) F ID_CLASIFICA VARCHAR2 (10 BYTE) F ID_CARGO_SUP VARCHAR2 (10 BYTE) DESCRIP VARCHAR2 (1024 BYTE) FUNCION VARCHAR2 (1024 BYTE) PROPOSITO VARCHAR2 (1024 BYTE) USRCRE VARCHAR2 (60 BYTE) FECCRE DATE USRACT VARCHAR2 (60 BYTE) FECACT DATE RIESGO VARCHAR2 (1024 BYTE)
AMCOR.NMM019
PF* CIA_CODCIA VARCHAR2 (4 BYTE) PF* TNOM_TIPNOM VARCHAR2 (4 BYTE) PF* PROC_TIPPRO NUMBER (2) PF* FPRO_SUBPRO NUMBER (1) PF* FPRO_ANOCAL NUMBER (4) PF* FPRO_NUMPER NUMBER (3) P * USERMO VARCHAR2 (30 BYTE) P * MODMOV VARCHAR2 (4 BYTE) P * SECMOV NUMBER (7) P * SUBSEC NUMBER (7) * TRAB_SUBTIP VARCHAR2 (1 BYTE) F * TRAB_FICTRA VARCHAR2 (10 BYTE) F * CTO_CODCTO NUMBER (4) * CANMOV NUMBER (14,7) * MONMOV NUMBER (25,9) DIAESQ VARCHAR2 (1 BYTE) * SUEVIE VARCHAR2 (1 BYTE) * TIPSUE VARCHAR2 (1 BYTE) FECMOV DATE F TRAB_FICSUS VARCHAR2 (10 BYTE) F TABU_CODTAB VARCHAR2 (6 BYTE) * VALSUS NUMBER (25,9) * FACSUS NUMBER (22,10) * NOSUMA VARCHAR2 (1 BYTE) * YACONT VARCHAR2 (1 BYTE) CTACON VARCHAR2 (36 BYTE) DEPALT VARCHAR2 (16 BYTE) ORDTRA VARCHAR2 (10 BYTE) CODOPE VARCHAR2 (6 BYTE) MRETRO VARCHAR2 (1 BYTE) USRCRE VARCHAR2 (30 BYTE) FECCRE DATE USRACT VARCHAR2 (30 BYTE) FECACT DATE DESADI VARCHAR2 (50 BYTE) MONCUO NUMBER (33,14) SALDOT NUMBER (25,9) INIDES DATE * ABONAR VARCHAR2 (1 BYTE) F ID_MOTIVO_HE VARCHAR2 (10 BYTE)
AMCOR.EO_PERSONA
P * ID NUMBER (20) * NOMBRE1 VARCHAR2 (17 BYTE) NOMBRE2 VARCHAR2 (15 BYTE) * APELLIDO1 VARCHAR2 (17 BYTE) APELLIDO2 VARCHAR2 (15 BYTE) F ID_TIPO_IDEN VARCHAR2 (2 BYTE) * NACIONAL VARCHAR2 (50 BYTE) NUM_IDEN VARCHAR2 (20 BYTE) PASAPORTE VARCHAR2 (10 BYTE) * FECHA_NA DATE CIUDAD_NA VARCHAR2 (30 BYTE) ID_ENTFE_NA VARCHAR2 (4 BYTE) ID_PAIS_NA VARCHAR2 (4 BYTE) * SEXO VARCHAR2 (1 BYTE) EDO_CIVIL VARCHAR2 (30 BYTE) * ZURDO NUMBER (1) TIPO_SANGRE VARCHAR2 (2 BYTE) FACTOR_RH VARCHAR2 (1 BYTE) DIRECCION VARCHAR2 (120 BYTE) CIUDAD VARCHAR2 (30 BYTE) ID_ENTFE VARCHAR2 (4 BYTE) ID_PAIS VARCHAR2 (4 BYTE) PARROQUIA VARCHAR2 (64 BYTE) MUNICIPIO VARCHAR2 (64 BYTE) COD_POSTAL VARCHAR2 (10 BYTE) TELEFONO1 VARCHAR2 (15 BYTE) TELEFONO2 VARCHAR2 (15 BYTE) FAX VARCHAR2 (15 BYTE) CELULAR VARCHAR2 (15 BYTE) E_MAIL1 VARCHAR2 (60 BYTE) E_MAIL2 VARCHAR2 (60 BYTE) IN_REL_TRAB VARCHAR2 (1 BYTE) USRCRE VARCHAR2 (60 BYTE) FECCRE DATE USRACT VARCHAR2 (60 BYTE) FECACT DATE NOMBRE_FOTO VARCHAR2 (128 BYTE)
AMCOR.EO_EMPRESA
P * ID VARCHAR2 (4 BYTE) * NOMBRE VARCHAR2 (70 BYTE) CLAVE VARCHAR2 (20 BYTE) NOMBRE_ABREV VARCHAR2 (30 BYTE) SECTOR_EMP VARCHAR2 (30 BYTE) * PUBLICA VARCHAR2 (1 BYTE) CAPITAL_PAG NUMBER (25,9) CAPITAL_SUB NUMBER (25,9) RIF1 VARCHAR2 (15 BYTE) RIF2 VARCHAR2 (15 BYTE) DIRECCION VARCHAR2 (120 BYTE) CIUDAD VARCHAR2 (30 BYTE) ID_ENTFE VARCHAR2 (4 BYTE) ID_PAIS VARCHAR2 (4 BYTE) COD_POSTAL VARCHAR2 (10 BYTE) TELEFONO1 VARCHAR2 (15 BYTE) TELEFONO2 VARCHAR2 (15 BYTE) FAX VARCHAR2 (15 BYTE) PAGINA_WEB VARCHAR2 (60 BYTE) E_MAIL VARCHAR2 (60 BYTE) FE_FUNDA DATE FE_INICIO DATE USRCRE VARCHAR2 (60 BYTE) FECCRE DATE USRACT VARCHAR2 (60 BYTE) FECACT DATE FILEMAIL VARCHAR2 (60 BYTE)
AMCOR.NMT033
PF* CIA_CODCIA VARCHAR2 (4 BYTE) PF* TNOM_TIPNOM VARCHAR2 (4 BYTE) PF* PROC_TIPPRO NUMBER (2) P * SUBPRO NUMBER (1) P * ANOCAL NUMBER (4) P * NUMPER NUMBER (3) DESPER VARCHAR2 (30 BYTE) * FECINI DATE * FECFIN DATE FECPAG DATE * MESCAL NUMBER (2) * NUMNOM NUMBER (1) * ULTNOM VARCHAR2 (1 BYTE) F FORPAG VARCHAR2 (1 BYTE) * ESTPER VARCHAR2 (1 BYTE) * PRORET VARCHAR2 (1 BYTE) FECSAL DATE F FPRO_TIPPRO NUMBER (2) F FPRO_SUBPRO NUMBER (1) F FPRO_ANOCAL NUMBER (4) F FPRO_NUMPER NUMBER (3) CUOSAL NUMBER (7,3) CUOREG NUMBER (7,3) TIPCOM VARCHAR2 (2 BYTE) NUMCOM VARCHAR2 (36 BYTE) FECCOM DATE ANOCON NUMBER (4) MESCON NUMBER (2) * FUNDIF VARCHAR2 (1 BYTE) TIPDIF VARCHAR2 (2 BYTE) NUMDIF VARCHAR2 (36 BYTE) FECDIF DATE ANODIF NUMBER (4) MESDIF NUMBER (2) FACDIF NUMBER (22,10) F FPRO_TIPPR1 NUMBER (2) F FPRO_SUBPR1 NUMBER (1) F FPRO_ANOCA1 NUMBER (4) F FPRO_NUMPE1 NUMBER (3) F STAT_CODSTA VARCHAR2 (4 BYTE) * BUSCOL VARCHAR2 (1 BYTE) FECIND DATE FECINH DATE FECRED DATE FECREH DATE * UNITIE VARCHAR2 (1 BYTE) * TIEFRC NUMBER (5) * DIAING NUMBER (2) * DIARET NUMBER (2) * TIPFED NUMBER (2) * TIPFEF NUMBER (2) * TIPFEH NUMBER (2) USRCRE VARCHAR2 (30 BYTE) FECCRE DATE USRACT VARCHAR2 (30 BYTE) FECACT DATE FECHA1 DATE FECHA2 DATE FECHA3 DATE FECESQ DATE FECRET DATE MDES_CODDES VARCHAR2 (4 BYTE) INIANI DATE FINANI DATE POSCOM VARCHAR2 (36 BYTE) POSDIF VARCHAR2 (36 BYTE)
AMCOR.RS_CV
P * ID NUMBER (10) F * ID_PERSONA NUMBER (20) AREA_ASPIRA VARCHAR2 (50 BYTE) CARGO_ASPIRA VARCHAR2 (50 BYTE) DISPONIBLE VARCHAR2 (50 BYTE) SITUACION VARCHAR2 (50 BYTE) IDIOMA_MATERNO VARCHAR2 (50 BYTE) ANOS_EXPERIENCIA NUMBER (2) VIAJAR VARCHAR2 (1 BYTE) RESIDENCIA VARCHAR2 (1 BYTE) VEHICULO VARCHAR2 (1 BYTE) MANEJO_PC VARCHAR2 (50 BYTE) HORARIO VARCHAR2 (30 BYTE) MODALIDAD VARCHAR2 (30 BYTE) SUELDO_MEN_ACT NUMBER (18,2) SUELDO_ANUAL_ACT NUMBER (18,2) MONEDA_ACT VARCHAR2 (50 BYTE) SUELDO_MEN_ASP NUMBER (18,2) SUELDO_ANUAL_ASP NUMBER (18,2) MONEDA_ASP VARCHAR2 (50 BYTE) RANGO_SUELDO_ASP VARCHAR2 (50 BYTE) PAIS_PREFE1 VARCHAR2 (4 BYTE) ENTIDAD_PREFE1 VARCHAR2 (4 BYTE) PAIS_PREFE2 VARCHAR2 (4 BYTE) ENTIDAD_PREFE2 VARCHAR2 (4 BYTE) PAIS_PREFE3 VARCHAR2 (4 BYTE) ENTIDAD_PREFE3 VARCHAR2 (4 BYTE) VISAS VARCHAR2 (150 BYTE) USRCRE VARCHAR2 (60 BYTE) FECCRE DATE USRACT VARCHAR2 (60 BYTE) FECACT DATE PESO NUMBER (5,2) ESTATURA NUMBER (3,2) LENTES VARCHAR2 (1 BYTE) TIPO_VIVIENDA VARCHAR2 (1 BYTE) NUM_LICENCIA VARCHAR2 (12 BYTE) GRADO_LICENCIA VARCHAR2 (1 BYTE) SERVICIO_MILITAR VARCHAR2 (1 BYTE) LIBRETA_MILITAR VARCHAR2 (12 BYTE) CLASE_MILITAR VARCHAR2 (4 BYTE) DISTRITO_MILITAR VARCHAR2 (10 BYTE) CERTIFICADO_JUDICIAL VARCHAR2 (10 BYTE)
AMCOR.RS_REQUISICION
P * ID NUMBER (10) ID_EMPRESA VARCHAR2 (4 BYTE) F ID_PERSONA NUMBER (20) CARGO VARCHAR2 (50 BYTE) AREA VARCHAR2 (50 BYTE) MODALIDAD VARCHAR2 (30 BYTE) CIUDAD VARCHAR2 (30 BYTE) ENTIDAD VARCHAR2 (4 BYTE) PAIS VARCHAR2 (4 BYTE) ANOS_EXPER NUMBER (2) PERSONAS_REQ NUMBER (3) FEC_SOLICITUD DATE HORARIO VARCHAR2 (30 BYTE) MANEJO_PC VARCHAR2 (50 BYTE) VIAJAR VARCHAR2 (1 BYTE) RESIDENCIA VARCHAR2 (1 BYTE) VEHICULO VARCHAR2 (1 BYTE) SUELDO_MIN NUMBER (18,2) SUELDO_MAX NUMBER (18,2) MONEDA VARCHAR2 (50 BYTE) NACIONALIDAD VARCHAR2 (50 BYTE) SEXO VARCHAR2 (1 BYTE) EDAD_DESDE NUMBER (2) EDAD_HASTA NUMBER (2) EDO_CIVIL VARCHAR2 (30 BYTE) STATUS VARCHAR2 (20 BYTE) MOTIVO VARCHAR2 (1000 BYTE) USRCRE VARCHAR2 (60 BYTE) FECCRE DATE USRACT VARCHAR2 (60 BYTE) FECACT DATE
AMCOR.SS_ROL_OPCION
PF* ID_ROL VARCHAR2 (30 BYTE) PF* ID_SISTEMA VARCHAR2 (10 BYTE) PF* ID_MODULO VARCHAR2 (10 BYTE) PF* ID_OPCION VARCHAR2 (30 BYTE) * AUTORIZA_INS VARCHAR2 (1 BYTE) * AUTORIZA_ACT VARCHAR2 (1 BYTE) * AUTORIZA_ELI VARCHAR2 (1 BYTE) USRCRE VARCHAR2 (60 BYTE) FECCRE DATE USRACT VARCHAR2 (60 BYTE) FECACT DATE
AMCOR.SS_USUARIO_UNIDAD
PF* ID_USUARIO VARCHAR2 (60 BYTE) PF* ID_EMPRESA VARCHAR2 (4 BYTE) PF* ID_UNIDAD VARCHAR2 (16 BYTE) USRCRE VARCHAR2 (60 BYTE) FECCRE DATE USRACT VARCHAR2 (60 BYTE) FECACT DATE
AMCOR.NM_RELACION_PAGO
PF* ID_EMPRESA VARCHAR2 (4 BYTE) PF* FICHA VARCHAR2 (10 BYTE) F ID_NOMINA VARCHAR2 (4 BYTE) F ID_GRUPO VARCHAR2 (2 BYTE) F ID_ROTACION NUMBER (2) F ID_DIS_NOMINA VARCHAR2 (4 BYTE) ID_EXCEPCION VARCHAR2 (10 BYTE) F ID_PROCESO NUMBER (2) F SUB_PROCESO NUMBER (1) F ANO_PERIODO NUMBER (4) F NRO_PERIODO NUMBER (3) F ID_DESCANSO VARCHAR2 (10 BYTE) USRCRE VARCHAR2 (60 BYTE) FECCRE DATE USRACT VARCHAR2 (60 BYTE) FECACT DATE
AMCOR.NMT027
PF* CIA_CODCIA VARCHAR2 (4 BYTE) PF* TNOM_TIPNOM VARCHAR2 (4 BYTE) P * CODCTO NUMBER (4) * DESCTO VARCHAR2 (30 BYTE) CLAUSU VARCHAR2 (4 BYTE) * FUNCTO VARCHAR2 (1 BYTE) * PRIEJE NUMBER (4) * MANSAL VARCHAR2 (1 BYTE) F CTOAFE NUMBER (4) * TIPCAL NUMBER (2) TIPFIS NUMBER (2) RUTCAL VARCHAR2 (10 BYTE) * VALCTO NUMBER (25,9) * SUEVAL VARCHAR2 (1 BYTE) F PROM_PROVAL VARCHAR2 (4 BYTE) * SERVAL VARCHAR2 (1 BYTE) * VALMES VARCHAR2 (1 BYTE) * TIPSUE VARCHAR2 (1 BYTE) F PROM_CODPRO VARCHAR2 (4 BYTE) * SUSSUE VARCHAR2 (1 BYTE) F PROM_PROSUS VARCHAR2 (4 BYTE) * FACCTO NUMBER (22,10) * SUEFAC VARCHAR2 (1 BYTE) F PROM_PROFAC VARCHAR2 (4 BYTE) * SERFAC VARCHAR2 (1 BYTE) * FACMES VARCHAR2 (1 BYTE) DESFAC VARCHAR2 (256 BYTE) * CANCTO NUMBER (7,3) * SUECAN VARCHAR2 (1 BYTE) F PROM_PROCA1 VARCHAR2 (4 BYTE) * SERCAN VARCHAR2 (1 BYTE) F PROM_PROCAN VARCHAR2 (4 BYTE) * CANMES VARCHAR2 (1 BYTE) * CANDIA NUMBER (1) * CONLIM VARCHAR2 (1 BYTE) * CANLID NUMBER (7,3) * CANLIH NUMBER (7,3) F PROM_PROLI1 VARCHAR2 (4 BYTE) * LIMINF NUMBER (25,9) * LIMSUP NUMBER (25,9) * LIMSUE VARCHAR2 (1 BYTE) F PROM_PROLIM VARCHAR2 (4 BYTE) * PROPE1 VARCHAR2 (1 BYTE) * PROPE2 VARCHAR2 (1 BYTE) * PROPE3 VARCHAR2 (1 BYTE) * PROPE4 VARCHAR2 (1 BYTE) * PROPE5 VARCHAR2 (1 BYTE) * AUTPRO VARCHAR2 (1 BYTE) * PROFIJ VARCHAR2 (1 BYTE) * CONEXC VARCHAR2 (1 BYTE) * PROANI VARCHAR2 (1 BYTE) TIPFEA NUMBER (1) * FIJING VARCHAR2 (1 BYTE) * AFEREG VARCHAR2 (1 BYTE) * POSVAC VARCHAR2 (1 BYTE) * CONABO VARCHAR2 (1 BYTE) * CALABO VARCHAR2 (1 BYTE) * CONCUO VARCHAR2 (1 BYTE) F CTOPRO NUMBER (4) * DIFCON VARCHAR2 (1 BYTE) * DISCEN VARCHAR2 (1 BYTE) * DISCON VARCHAR2 (1 BYTE) CTACO1 VARCHAR2 (36 BYTE) POSRE1 VARCHAR2 (36 BYTE) CTACO2 VARCHAR2 (36 BYTE) POSRE2 VARCHAR2 (36 BYTE) F CTOFIJ NUMBER (4) F CTOINT NUMBER (4) * NONETO VARCHAR2 (1 BYTE) * NOIMPR VARCHAR2 (1 BYTE) * MANINS VARCHAR2 (1 BYTE) FACAHO NUMBER (22,10) F CTOAHO NUMBER (4) * UNASUP VARCHAR2 (1 BYTE) F CTOSUP NUMBER (4) * GRAIMP VARCHAR2 (1 BYTE) * SINDEC VARCHAR2 (1 BYTE) FACIMP NUMBER (22,10) * TOPSUE VARCHAR2 (1 BYTE) * TOPVAL VARCHAR2 (1 BYTE) * TOPFAC VARCHAR2 (1 BYTE) * TOPCAN VARCHAR2 (1 BYTE) * BUSSUC VARCHAR2 (1 BYTE) * BUSSUF VARCHAR2 (1 BYTE) * BUSSUV VARCHAR2 (1 BYTE) * SUECAC VARCHAR2 (1 BYTE) * SUECAF VARCHAR2 (1 BYTE) * SUECAV VARCHAR2 (1 BYTE) * SUELIM VARCHAR2 (1 BYTE) * TOPMON VARCHAR2 (1 BYTE) * INCDET VARCHAR2 (1 BYTE) * ABOPRE VARCHAR2 (1 BYTE) CTO_INTPRE NUMBER (4) * CAPINT VARCHAR2 (1 BYTE) * ACUCHE VARCHAR2 (1 BYTE) * CRETRO VARCHAR2 (1 BYTE) * GRETRO VARCHAR2 (1 BYTE) CODBEN VARCHAR2 (10 BYTE) USRCRE VARCHAR2 (30 BYTE) FECCRE DATE USRACT VARCHAR2 (30 BYTE) FECACT DATE * SALMIN NUMBER (3) * SALMIS NUMBER (3) * SALMIV VARCHAR2 (1 BYTE) * SALMIC VARCHAR2 (1 BYTE) * SALMIF VARCHAR2 (1 BYTE) * SALMIL VARCHAR2 (1 BYTE) RUTSUS VARCHAR2 (10 BYTE) * FACAFE NUMBER (22,10) * FACFIJ NUMBER (22,10) * FACCEN VARCHAR2 (1 BYTE) * MONTOCERO VARCHAR2 (1 BYTE) * INACTIVO VARCHAR2 (1 BYTE) * SUSCUOTA VARCHAR2 (1 BYTE)
AMCOR.TA_PRIMA_PLAN
P * CODE_PK NUMBER (20) * NOMBRE VARCHAR2 (64 BYTE) * TIPO VARCHAR2 (32 BYTE) USRCRE VARCHAR2 (60 BYTE) FECCRE DATE USRACT VARCHAR2 (60 BYTE) FECACT DATE
AMCOR.TA_PLANES_COBERTURAS
PF* CODE_PLAN NUMBER (20) P * CODE_COBERTURA NUMBER (20) * MONTO_COBERTURA NUMBER (25,9) USRCRE VARCHAR2 (60 BYTE) FECCRE DATE USRACT VARCHAR2 (60 BYTE) FECACT DATE
`;

function parseOCR(text) {
    const tables = {};
    let currentTable = null;
    
    // Normalize flags (OCR tends to add spaces)
    text = text.replace(/PF\*[ ]+/g, 'PF*').replace(/P \*[ ]+/g, 'P*').replace(/F \*[ ]+/g, 'F*');
    
    const lines = text.split('\n');
    for (let line of lines) {
        line = line.trim();
        if (!line) continue;
        
        const tableMatch = line.match(/^AMCOR\.([A-Z0-9_]+)/);
        if (tableMatch) {
            currentTable = tableMatch[1];
            tables[currentTable] = { columns: [], description: "" };
            continue;
        }
        
        if (!currentTable) continue;
        
        // Match columns
        // We look for patterns like: PF* NAME TYPE (OPT_BYTE) or NAME TYPE
        // Regex: (FLAGS)? (NAME) (TYPE) ( (LEN)? (BYTE)? )?
        const colRegex = /([PF\*]+)\s*([A-Z0-9_]+)\s+([A-Z]+[0-9]*\b(?:\s*\(.*?\))?)/g;
        let match;
        while ((match = colRegex.exec(line)) !== null) {
            const flags = match[1];
            const name = match[2];
            const type = match[3];
            
            if (name === "AMCOR" || name === "VARCHAR2" || name === "NUMBER" || name === "DATE") continue;
            
            tables[currentTable].columns.push({
                name,
                type,
                pk: flags.includes('P'),
                fk: flags.includes('F')
            });
        }
    }
    return tables;
}

function getModule(tname) {
    if (tname.startsWith('NM')) return { name: 'Nómina', icon: '📊' };
    if (tname.startsWith('SPI') || tname.startsWith('SS')) return { name: 'Seguridad', icon: '🛡️' };
    if (tname.startsWith('EO')) return { name: 'Estructura', icon: '🏢' };
    if (tname.startsWith('AR')) return { name: 'Configuración', icon: '⚙️' };
    if (tname.startsWith('RH')) return { name: 'RRHH', icon: '📜' };
    if (tname.startsWith('TA')) return { name: 'Maestras', icon: '📋' };
    if (tname.startsWith('RS')) return { name: 'Reclutamiento', icon: '👥' };
    return { name: 'Otros', icon: '📦' };
}

async function generate() {
    const data = parseOCR(ocrText);
    const outputDir = 'b:/Antigravity/BD_Infocent/docs';
    
    if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true });

    let tableCards = "";
    const sortedNames = Object.keys(data).sort();
    
    for (const tname of sortedNames) {
        const info = data[tname];
        const mod = getModule(tname);
        
        let rows = info.columns.map(c => `
            <tr>
                <td><span class="${c.pk ? 'pk' : (c.fk ? 'fk' : '')}">${c.name}</span></td>
                <td>${c.type}</td>
                <td>${c.pk ? 'PRIMARY KEY' : ''} ${c.fk ? 'FOREIGN KEY' : ''}</td>
            </tr>
        `).join("");

        tableCards += `
        <div class="table-card table-item" id="${tname}" data-name="${tname}" style="margin-top: 3rem;">
            <div style="display:flex; justify-content: space-between; align-items: center; margin-bottom: 1rem;">
                <h3 style="color: var(--accent); margin:0;">${mod.icon} AMCOR.${tname}</h3>
                <span class="table-tag">${mod.name}</span>
            </div>
            <table class="data-table">
                <thead>
                    <tr><th>Campo</th><th>Tipo</th><th>Constraint</th></tr>
                </thead>
                <tbody>${rows}</tbody>
            </table>
        </div>
        `;
    }

    const html = `
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Diccionario Completo - Infocent</title>
    <link rel="stylesheet" href="style.css">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;800&display=swap" rel="stylesheet">
    <style>
        .pk { color: #f87171; font-weight: bold; }
        .fk { color: #4ade80; font-weight: bold; }
        .search-container { position: sticky; top: 0; background: var(--bg-dark); padding: 1rem 0; z-index: 1000; border-bottom: 1px solid var(--border); }
    </style>
</head>
<body>
    <header>
        <h1>Diccionario Universal de Datos</h1>
        <p style="color: var(--text-muted);">${sortedNames.length} Tablas Documentadas</p>
    </header>

    <div class="container">
        <nav><a href="index.html">Resumen</a><a href="relaciones.html">Entidad-Relación</a></nav>

        <div class="search-container">
            <input type="text" id="masterSearch" class="search-box" placeholder="Buscar por nombre de tabla..." onkeyup="filter()">
        </div>

        <div id="tableList">
            ${tableCards}
        </div>
    </div>

    <script>
        function filter() {
            let q = document.getElementById('masterSearch').value.toUpperCase();
            let cards = document.getElementsByClassName('table-card');
            for(let card of cards) {
                let name = card.getAttribute('data-name');
                card.style.display = name.includes(q) ? "block" : "none";
            }
        }
    </script>
</body>
</html>`;

    fs.writeFileSync(path.join(outputDir, 'diccionario_completo.html'), html);
    console.log("Generado diccionario_completo.html con " + sortedNames.length + " tablas.");
}

generate();
